/**
 * Generate src/data/qr-site.ts — the QR code for the site's own URL.
 *
 * The More sheet offers a crewmember three ways to pass the site on: the OS
 * share sheet, the clipboard, and a code someone else can point a camera at.
 * The third one is the reason this script exists.
 *
 * WHY BUILD TIME AND NOT A RUNTIME LIBRARY
 *
 * The URL never changes, so encoding it in the browser would ship a QR
 * generator to every visitor to compute the same 29×29 grid every time. Worse,
 * it would compute nothing at all offline if the library were lazy-loaded —
 * and "no signal" is the exact situation where someone reads a code off a
 * phone screen instead of typing a URL.
 *
 * The output is the path data, not an <svg>: the component owns the markup, so
 * sizing, colour and the accessible name live where the rest of the UI does.
 * Dark modules are merged into horizontal runs, which is a third of the size of
 * one rect per module and renders identically.
 *
 * Runs ahead of `astro build`, like gen-icons. The output is committed so
 * `astro dev` works without it; the build regenerates to catch drift.
 */

import { readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import qrcode from 'qrcode-generator';

import { SRC, forDisplay } from './lib/paths.mjs';

const SITE = join(SRC, 'data/site.ts');
const OUT = join(SRC, 'data/qr-site.ts');

/** The URL comes from SITE.url — one definition, so the code can't encode a stale host. */
const url = readFileSync(SITE, 'utf8').match(/url:\s*'([^']+)'/)?.[1];
if (!url) {
  console.error(`\ngen-qr: no \`url: '…'\` found in ${forDisplay(SITE)}\n`);
  process.exit(1);
}

/**
 * Error correction M — 15% recoverable. L would make the grid smaller, but the
 * code gets read off a scuffed phone screen at an angle, often in a dim galley.
 */
const qr = qrcode(0, 'M');
qr.addData(url);
qr.make();

const modules = qr.getModuleCount();

/** One `M…h…v1h-…z` per horizontal run of dark modules. */
let path = '';
for (let row = 0; row < modules; row++) {
  let col = 0;
  while (col < modules) {
    if (!qr.isDark(row, col)) {
      col++;
      continue;
    }
    const start = col;
    while (col < modules && qr.isDark(row, col)) col++;
    path += `M${start} ${row}h${col - start}v1h-${col - start}z`;
  }
}

/** Four modules is the spec's quiet zone; two is enough against a white card. */
const QUIET = 2;

writeFileSync(
  OUT,
  `/* ============================================================
   Blue Streak Hangar — site QR code
   ------------------------------------------------------------
   GENERATED by scripts/gen-qr.mjs — do not edit by hand.
   Regenerate with \`node scripts/gen-qr.mjs\`; the build runs it
   ahead of \`astro build\`.

   Encodes ${url} at error-correction level M.
   Rendered by components/MobileNav.astro.
   ============================================================ */

export const SITE_QR = {
  /** What the code resolves to. */
  url: '${url}',
  /** Modules per side, excluding the quiet zone. */
  modules: ${modules},
  /** Quiet zone, in modules, on every side. */
  quiet: ${QUIET},
  /** viewBox side: modules plus a quiet zone at each edge. */
  side: ${modules + QUIET * 2},
  /** Dark modules, merged into horizontal runs. Draw at translate(quiet, quiet). */
  path: '${path}',
} as const;
`,
);

console.log(`gen-qr: ${modules}×${modules} modules, ${path.length} path chars → ${forDisplay(OUT)}`);
